blank_issues_enabled: false
contact_links:
  - name: Private Support Ticket
    url: https://docs.solspace.com/craft/freeform/v3/support.html
    about: Create a private support ticket.
  - name: Freeform Documentation
    url: https://docs.solspace.com/craft/freeform/v3/
    about: Read the official documentation.
  - name: Craft Stack Exchange
    url: https://craftcms.stackexchange.com/questions/tagged/solspace
    about: Research or gather information and advice from all over the Craft community.