name: Builder

on:
  pull_request:
    branches: [v5]

jobs:
  ts-linter:
    runs-on: ubuntu-latest
    name: Linter

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Set up Font Awesome Pro
        run: |
          echo "@fortawesome:registry=https://npm.fontawesome.com/" >> .npmrc
          echo "//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}" >> .npmrc

      - name: npm ci
        run: npm ci

      - name: npm run lint
        run: |
          cd packages/client
          npm run lint

  ts-tests:
    runs-on: ubuntu-latest
    name: Tests

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Set up Font Awesome Pro
        run: |
          echo "@fortawesome:registry=https://npm.fontawesome.com/" >> .npmrc
          echo "//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}" >> .npmrc

      - name: npm ci
        run: npm ci

      - name: npm test
        run: |
          cd packages/client
          npm test
