name: Continuous Integration

on:
  pull_request:
    branches: [v5.0]

env:
  CI: true

jobs:
  ts-linter:
    runs-on: ubuntu-latest
    name: Typescript Code Style Check

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: npm run lint

  ts-tests:
    runs-on: ubuntu-latest
    name: TypeScript tests

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: npm run lint
      - run: npm test

  php-lint:
    runs-on: ubuntu-latest
    name: PHP Code Style Check

    strategy:
      matrix:
        php-versions: ['8.0.2']

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: curl, mbstring, gd

      # Cache the vendors directory to spend less resources on each run
      - name: Cache vendors
        uses: actions/cache@v1
        with:
          path: vendor/
          key: vendors-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run CS Fixer
        run: composer run fix:dry-run || (printf \"\\e[41mCS Fixer found issues\\e[0m\\n\" && exit 1)

  php-tests:
    runs-on: ubuntu-latest
    name: PHP Unit & Acceptance tests

    strategy:
      matrix:
        php-versions: ['8.0.2']

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: curl, mbstring, gd

      # Cache the vendors directory to spend less resources on each run
      - name: Cache vendors
        uses: actions/cache@v1
        with:
          path: vendor/
          key: vendors-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Unit Tests
        run: composer run-script test:unit
